---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Initial test of local repository (testing.yaml)
      - name: "Running local action: ${{ github.repository }}"
        uses: ./

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: 'test-python-project'

      # Test downloaded sample Python project
      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [test-python-project]"
        uses: ./
        with:
          path_prefix: 'test-python-project'
          no_checkout: true

      # yamllint disable-line rule:line-length
      - name: "Running local action: ${{ github.repository }} [Override Failure]"
        uses: ./
        id: failure
        continue-on-error: true
        with:
          path_prefix: "/tmp/invalid-path"

      # Failure testing is also important
      - name: "Error if step above did NOT fail"
        if: steps.failure.outcome == 'success'
        shell: bash
        run: |
          # Error if step above did NOT fail
          echo "Error: previous test step did NOT fail ❌"
          exit 1
